/*
 * Camera data is deliberately separate from the UI.
 * Add a camera by copying one object and keeping the same keys.
 * Checked against manufacturers' Japanese product/specification pages on 2026-08-01.
 */
window.CAMERAS = [
  {id:'sony-a1-ii',brand:'Sony',model:'α1 II',mount:'Sony E',sensor:'Full Frame',mp:50.1,ibis:true,burst:'30 fps',burstValue:30,video:'8K 30p / 4K 120p',weight:743,released:'2024-12',purpose:['photo','hybrid','speed'],official:'https://www.sony.jp/ichigan/products/ILCE-1M2/'},
  {id:'sony-a9-iii',brand:'Sony',model:'α9 III',mount:'Sony E',sensor:'Full Frame',mp:24.6,ibis:true,burst:'120 fps',burstValue:120,video:'4K 120p',weight:702,released:'2024-01',purpose:['photo','speed'],official:'https://www.sony.jp/ichigan/products/ILCE-9M3/'},
  {id:'sony-a7r-vi',brand:'Sony',model:'α7R VI',mount:'Sony E',sensor:'Full Frame',mp:66.8,ibis:true,burst:'30 fps',burstValue:30,video:'4K 60p',weight:723,released:'2026-04',purpose:['photo','hybrid'],official:'https://www.sony.jp/ichigan/products/ILCE-7RM6/'},
  {id:'sony-a7-iv',brand:'Sony',model:'α7 IV',mount:'Sony E',sensor:'Full Frame',mp:33.0,ibis:true,burst:'10 fps',burstValue:10,video:'4K 60p',weight:658,released:'2021-12',purpose:['hybrid'],official:'https://www.sony.jp/ichigan/products/ILCE-7M4/'},

  {id:'canon-r1',brand:'Canon',model:'EOS R1',mount:'Canon RF',sensor:'Full Frame',mp:24.2,ibis:true,burst:'40 fps',burstValue:40,video:'6K 60p RAW / 4K 120p',weight:1115,released:'2024-11',purpose:['photo','hybrid','speed'],official:'https://personal.canon.jp/product/camera/eos/r1'},
  {id:'canon-r5-ii',brand:'Canon',model:'EOS R5 Mark II',mount:'Canon RF',sensor:'Full Frame',mp:45.0,ibis:true,burst:'30 fps',burstValue:30,video:'8K 60p RAW / 4K 120p',weight:746,released:'2024-08',purpose:['photo','hybrid'],official:'https://personal.canon.jp/product/camera/eos/r5mk2'},
  {id:'canon-r6-iii',brand:'Canon',model:'EOS R6 Mark III',mount:'Canon RF',sensor:'Full Frame',mp:32.5,ibis:true,burst:'40 fps',burstValue:40,video:'7K 60p RAW / Open Gate',weight:699,released:'2025-11',purpose:['hybrid','video','speed'],official:'https://personal.canon.jp/product/camera/eos/r6mk3'},
  {id:'canon-r8',brand:'Canon',model:'EOS R8',mount:'Canon RF',sensor:'Full Frame',mp:24.2,ibis:false,burst:'40 fps',burstValue:40,video:'4K 60p',weight:461,released:'2023-04',purpose:['hybrid'],official:'https://personal.canon.jp/product/camera/eos/r8'},

  {id:'nikon-z9',brand:'Nikon',model:'Z9',mount:'Nikon Z',sensor:'Full Frame',mp:45.7,ibis:true,burst:'20 fps RAW / 120 fps JPEG',burstValue:120,video:'8.3K 60p RAW / 4K 120p',weight:1340,released:'2021-12',purpose:['photo','hybrid','speed'],official:'https://www.nikon-image.com/products/mirrorless/lineup/z_9/'},
  {id:'nikon-z8',brand:'Nikon',model:'Z8',mount:'Nikon Z',sensor:'Full Frame',mp:45.7,ibis:true,burst:'20 fps RAW / 120 fps JPEG',burstValue:120,video:'8.3K 60p RAW / 4K 120p',weight:910,released:'2023-05',purpose:['photo','hybrid','speed'],official:'https://www.nikon-image.com/products/mirrorless/lineup/z_8/'},
  {id:'nikon-z6-iii',brand:'Nikon',model:'Z6III',mount:'Nikon Z',sensor:'Full Frame',mp:24.5,ibis:true,burst:'20 fps RAW / 120 fps JPEG',burstValue:120,video:'6K 60p RAW / 4K 120p',weight:760,released:'2024-07',purpose:['hybrid','video','speed'],official:'https://www.nikon-image.com/products/mirrorless/lineup/z6_3/'},
  {id:'nikon-zf',brand:'Nikon',model:'Zf',mount:'Nikon Z',sensor:'Full Frame',mp:24.5,ibis:true,burst:'14 fps RAW / 30 fps JPEG',burstValue:30,video:'4K 60p',weight:710,released:'2023-10',purpose:['photo','hybrid'],official:'https://www.nikon-image.com/products/mirrorless/lineup/z_f/'},

  {id:'fuji-gfx100s-ii',brand:'FUJIFILM',model:'GFX100S II',mount:'FUJIFILM G',sensor:'Medium Format',mp:102.0,ibis:true,burst:'7 fps',burstValue:7,video:'4K 30p',weight:883,released:'2024-06',purpose:['photo'],official:'https://www.fujifilm-x.com/ja-jp/products/cameras/gfx100s-ii/'},
  {id:'fuji-xh2s',brand:'FUJIFILM',model:'X-H2S',mount:'FUJIFILM X',sensor:'APS-C',mp:26.1,ibis:true,burst:'40 fps',burstValue:40,video:'6.2K 30p / 4K 120p',weight:660,released:'2022-07',purpose:['hybrid','video','speed'],official:'https://www.fujifilm-x.com/ja-jp/products/cameras/x-h2s/'},
  {id:'fuji-xh2',brand:'FUJIFILM',model:'X-H2',mount:'FUJIFILM X',sensor:'APS-C',mp:40.2,ibis:true,burst:'20 fps',burstValue:20,video:'8K 30p / 4K 60p',weight:660,released:'2022-09',purpose:['photo','hybrid'],official:'https://www.fujifilm-x.com/ja-jp/products/cameras/x-h2/'},
  {id:'fuji-xt5',brand:'FUJIFILM',model:'X-T5',mount:'FUJIFILM X',sensor:'APS-C',mp:40.2,ibis:true,burst:'20 fps',burstValue:20,video:'6.2K 30p / 4K 60p',weight:557,released:'2022-11',purpose:['photo','hybrid'],official:'https://www.fujifilm-x.com/ja-jp/products/cameras/x-t5/'},
  {id:'fuji-xs20',brand:'FUJIFILM',model:'X-S20',mount:'FUJIFILM X',sensor:'APS-C',mp:26.1,ibis:true,burst:'20 fps',burstValue:20,video:'6.2K 30p / 4K 60p',weight:491,released:'2023-06',purpose:['hybrid','video'],official:'https://www.fujifilm-x.com/ja-jp/products/cameras/x-s20/'},

  {id:'lumix-s1rii',brand:'Panasonic',model:'LUMIX S1RII',mount:'L-Mount',sensor:'Full Frame',mp:44.3,ibis:true,burst:'40 fps',burstValue:40,video:'8K 30p / 4K 120p',weight:795,released:'2025-03',purpose:['photo','hybrid','video'],official:'https://panasonic.jp/dc/products/DC-S1RM2.html'},
  {id:'lumix-s1ii',brand:'Panasonic',model:'LUMIX S1II',mount:'L-Mount',sensor:'Full Frame',mp:24.1,ibis:true,burst:'70 fps',burstValue:70,video:'5.8K 60p / 4K 120p',weight:800,released:'2025-06',purpose:['hybrid','video','speed'],official:'https://panasonic.jp/dc/products/DC-S1M2.html'},
  {id:'lumix-s1iie',brand:'Panasonic',model:'LUMIX S1IIE',mount:'L-Mount',sensor:'Full Frame',mp:24.2,ibis:true,burst:'30 fps',burstValue:30,video:'6K 30p / 4K 60p',weight:795,released:'2025-06',purpose:['hybrid','video'],official:'https://panasonic.jp/dc/products/DC-S1M2ESM.html'},
  {id:'lumix-s5iix',brand:'Panasonic',model:'LUMIX S5IIX',mount:'L-Mount',sensor:'Full Frame',mp:24.2,ibis:true,burst:'30 fps',burstValue:30,video:'6K 30p / 4K 60p',weight:740,released:'2023-06',purpose:['hybrid','video'],official:'https://panasonic.jp/dc/products/DC-S5M2X.html'},
  {id:'lumix-gh7',brand:'Panasonic',model:'LUMIX GH7',mount:'Micro Four Thirds',sensor:'Micro Four Thirds',mp:25.2,ibis:true,burst:'75 fps',burstValue:75,video:'5.7K 60p / 4K 120p',weight:805,released:'2024-07',purpose:['hybrid','video','speed'],official:'https://panasonic.jp/dc/products/DC-GH7.html'},

  {id:'om-1-ii',brand:'OM SYSTEM',model:'OM-1 Mark II',mount:'Micro Four Thirds',sensor:'Micro Four Thirds',mp:20.4,ibis:true,burst:'120 fps S-AF / 50 fps C-AF',burstValue:120,video:'C4K 60p',weight:599,released:'2024-02',purpose:['photo','speed'],official:'https://jp.omsystem.com/product/dslr/om-omd/om/om1mk2/'},
  {id:'om-3',brand:'OM SYSTEM',model:'OM-3',mount:'Micro Four Thirds',sensor:'Micro Four Thirds',mp:20.4,ibis:true,burst:'120 fps S-AF / 50 fps C-AF',burstValue:120,video:'C4K 60p',weight:496,released:'2025-03',purpose:['photo','hybrid','speed'],official:'https://jp.omsystem.com/product/dslr/om-omd/om/om3/'},
  {id:'om-5-ii',brand:'OM SYSTEM',model:'OM-5 Mark II',mount:'Micro Four Thirds',sensor:'Micro Four Thirds',mp:20.4,ibis:true,burst:'30 fps',burstValue:30,video:'C4K 24p / 4K 30p',weight:418,released:'2025-07',purpose:['photo','hybrid'],official:'https://jp.omsystem.com/product/dslr/om-omd/om/om5mk2/'},
  {id:'pen-ep7',brand:'OM SYSTEM',model:'OLYMPUS PEN E-P7',mount:'Micro Four Thirds',sensor:'Micro Four Thirds',mp:20.3,ibis:true,burst:'15 fps',burstValue:15,video:'4K 30p',weight:337,released:'2021-06',purpose:['photo'],official:'https://jp.omsystem.com/product/dslr/pen/ep7/'}
];
